#!/bin/sh
#
# This script will work on macos and linux
# 

pdversion=0.51-0
patchname=quaker.pd


dir=$(dirname ${BASH_SOURCE[0]})
patch=${dir}/${patchname}
pd51="http://msp.ucsd.edu/Software/pd-${pdversion}.mac.tar.gz"
apppd="~/Applications/Pd-${pdversion}.app/Contents/Resources/bin/pd"
localpd="${dir}/Pd-${pdversion}.app/Contents/Resources/bin/pd"


function check_version {
	local pd=$1

	if [[ $("$pd" -version 2>&1 | cut -f 2 -d.) -le "51" ]]
	then
		echo 1
	else
		echo 0
	fi

}

if [[ ! $(check_version "pd") ]]
then
	echo "Pd is not installed in your system."
	echo "Checking if you have it on the Applications directory..."
	if [[ ! $(check_version "$apppd") ]]
	then
		echo "Pd is not in your Applications directory."
		echo "Checking if you have a local copy on this directory..."
		if [[ ! $(check_version "$localpd") ]]
		then
			echo "Pd is not in your local dir."
			echo "Downloading pd..."
			curl $pd51 -o pd-0.51-0.mac.tar.gz
			tar xzf pd-0.51-0.mac.tar.gz
			if [[ ! $(check_version $localpd) ]]
			then
				echo "There was a problem downloading pd."
				echo "Please, go to msp.ucsd.edu, get Pd and place it here."
				echo "Exiting."
				exit 1
			else
				pd=$localpd
			fi
		else
			pd=$localpd
		fi
	else
		pd=$apppd
	fi
else
	pd=$(which pd)
fi

echo "Running pd from: $pd"

$pd -stderr -nogui $@ -send ";quack-start bang" -open $patch
