#!/bin/sh
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
patch=$DIR/quack3.pd
pd51="http://msp.ucsd.edu/Software/pd-0.51-0.mac.tar.gz"
localpd="$DIR/Pd-0.51-0.app/Contents/Resources/bin/pd"

function check_version {
	local pd=$1

	if [[ $("$pd" -version 2>&1 | cut -f 2 -d.) -le "51" ]]
	then
		echo 1
	else
		echo 0
	fi

}

if [[ ! $(check_version "pd") ]]
then
	echo "Pd is not installed in your system."
	echo "Checking if you have a local copy on this directory..."
	if [[ ! $(check_version "$localpd") ]]
	then
		echo "Pd is not in your local dir."
		echo "Downloading pd..."
		curl $pd51 -o pd-0.51-0.mac.tar.gz
		tar xzf pd-0.51-0.mac.tar.gz
		if [[ ! $(check_version $localpd) ]]
		then
			echo "There was a problem downloading pd."
			echo "Please, go to msp.ucsd.edu, download it and place it here."
			echo "Exitting."
			exit 1
		else
			pd=$localpd
		fi
	else
		pd=$localpd
	fi
else
	pd=$(which pd)
fi

echo "Running pd from: $pd"

$pd -stderr -nogui $@ -send ";quack-start-set 1; onoff-set 1" -open $patch
